### PR TITLE
Add code for card 4 and the used dataset

### PR DESCRIPTION
**Pull request by shyan0903**

### CODE REVIEW

**Comment by BooleanJulien** [comment]
Hey @shyan0903 can you explain why there is an additional dataset added in this PR?

**Comment by shyan0903** [comment]
@BooleanJulien As you mentioned last time about double checking the data that was used to calculate income per capita, I have found a data set, compiled by Gapminder from various sources, that is more reliable and has a clearer documentation. Moreover, the total GDP/income has been adjusted for inflation and converted to US dollar using purchasing power parity rates. Since the original and the new dataset does not have all the columns I need, I have joined the two to create this new dataset solely for the income per capita plot. Hope this explanation helps and I will also update the dataset in the Python app. Thanks!

**Comment by shyan0903** [comment]
@BooleanJulien Add to my last comment, when I compared the two datasets, the numbers for the income and the population were off a lot. So I chose to use the values from the newly found dataset with a clear documentation and was well maintained.

**Comment by BooleanJulien** [comment]
Ok thanks for the update! I'll make a note of this in the reflection

**Review by BooleanJulien — APPROVED** [review]
lgtm merging

**Comment by SonQBChau** [comment]
This is fine for R. On Python, it's a bit more complicated since I added a new part in your card, Irene. You can finish the plot first and I will copy the query over.

**Pull request merged**
